fix(placement-ordering): reposition elements using push instead of swap PD-42
pie-framework/pie-ui pull request #256
Opened 2021-03-03 11:17 UTC by PatriciaRomaniuc

https://illuminate.atlassian.net/browse/PD-42

2021-03-03 17:04 UTC, edeustace requested changes

2021-03-03 17:04 UTC, edeustace commented on packages/placement-ordering/src/ordering.js
>  export const swap = (arr, fromIndex, toIndex) => {
from the ticket - it seems that 'swap' is not to be used at all - in which case we should remove all reference to it, and adopt 'push' as the name of the action

2021-03-03 17:04 UTC, edeustace commented on packages/placement-ordering/src/__tests__/ordering.test.js
> +      assertPush([0, 1], [2, 1], [2, 3, 1, 4]);
can we have a look at using `it.each` for these tests? say: 

```javascript
describe('A,B,C,D', () => {
  /** 
   * read action string as 'value' to 'index' seperated by a comma
  */
  it.each`actions   | expected
              ${'D-0']} | ${ 'D,A,B,C'}
              ${'D-0,B-1']} | ${ 'D,B,A,C'}
`( "$actions => $expected" , () => {
    // parse actions, apply them and assert the result is as expected.
  });
});
```
see: https://jestjs.io/docs/en/api#testeachtablename-fn-timeout

2021-03-04 12:27 UTC, PatriciaRomaniuc commented on packages/placement-ordering/src/ordering.js
>  export const swap = (arr, fromIndex, toIndex) => {
The ticket refers to the No Placement Area behavior.

If Placement Area is OFF, the current behavior with choices order: A, B, C, D:
- if user drags D over A it replaces A with D (D, B, C, A) ('swap' from ticket)

I fixed this with:
- if user drags D over A it moves D at the top (D, A, B, C) ('push' from ticket)

The swap function is used for Placement Area ON.

2021-03-05 09:24 UTC, edeustace commented on packages/placement-ordering/src/ordering.js
>  export const swap = (arr, fromIndex, toIndex) => {
ah ok - nevermind so

2021-03-05 09:40 UTC, merged